version: '3'
services: 
  apache2:
    image: ajay1906/apache2-server:v1.0
    networks:
      - my-network
    ports:
      - "8080:80"
  haproxy:
    image: ajay1906/haproxy-main:v1.0
    networks:
      - my-network
    ports:
      - "80:80"
      - "90:90"
  nginx:
    image: ajay1906/nginx-server:v1.0
    networks:
      - my-network
    ports:
      - "8081:80"
networks:
  my-network:
    driver: bridge

